import type { BookmarkItem } from "@/lib/bookmark-item"

export interface Saint {
  id: string
  name: string
  title: string // e.g. "SAN", "SANTA", "BEATO", "BEATA"
  displayName: string // e.g. "Pedro"
  feastDay: string // e.g. "29 DE JUNIO"
  virtue: string // e.g. "CONFIANZA EN CRISTO"
  description: string
  period: string // e.g. "Siglo I a.C.-67 d.C."
  prayer: string // short prayer or sentence for the front
  image?: string // path to image if available
  watercolorFront: string // CSS color for front watercolor wash
  watercolorBack: string // CSS color for back watercolor wash
}

export const saints: Saint[] = [
  {
    id: "san-pedro",
    name: "San Pedro",
    title: "SAN",
    displayName: "Pedro",
    feastDay: "29 DE JUNIO",
    virtue: "CONFIANZA EN CRISTO",
    description: "Apostol de Jesus, el primero entre los discipulos en extender la Iglesia en Roma. Alli fue martirizado despues de testimoniar a Cristo entre hebreos y paganos.",
    prayer: "Tu eres Pedro, y sobre esta piedra edificare mi Iglesia.",
    period: "Siglo I a.C. - 67 d.C.",
    image: "/images/saints/san-pedro.jpg",
    watercolorFront: "#b8d4e3",
    watercolorBack: "#b5c9a8",
  },
  {
    id: "san-pablo",
    name: "San Pablo",
    title: "SAN",
    displayName: "Pablo",
    feastDay: "29 DE JUNIO",
    virtue: "CELO APOSTOLICO",
    description: "Apostol de los gentiles, convertido en el camino a Damasco. Escribio numerosas epistolas que forman parte del Nuevo Testamento y predico el Evangelio por todo el Mediterraneo.",
    prayer: "Ya no vivo yo, sino que Cristo vive en mi.",
    period: "5 d.C. - 67 d.C.",
    image: "/images/saints/san-pablo.jpg",
    watercolorFront: "#d4a8a8",
    watercolorBack: "#c9b8a8",
  },
  {
    id: "virgen-maria",
    name: "Virgen Maria",
    title: "VIRGEN",
    displayName: "Maria",
    feastDay: "1 DE ENERO",
    virtue: "HUMILDAD Y OBEDIENCIA",
    description: "Madre de Dios y Madre de la Iglesia. Elegida por Dios para ser la madre de Jesus, acepto con humildad y fe la voluntad divina. Es modelo de todas las virtudes cristianas.",
    prayer: "Hagase en mi segun tu Palabra.",
    period: "Siglo I a.C. - Siglo I d.C.",
    image: "/images/saints/virgen-maria.jpg",
    watercolorFront: "#a8c4d4",
    watercolorBack: "#d4c8e0",
  },
  {
    id: "san-jose",
    name: "San Jose",
    title: "SAN",
    displayName: "Jose",
    feastDay: "19 DE MARZO",
    virtue: "FIDELIDAD Y TRABAJO",
    description: "Esposo de la Virgen Maria y padre adoptivo de Jesus. Carpintero de oficio, protegio a la Sagrada Familia con su trabajo y silencio. Patron de los trabajadores y de la buena muerte.",
    prayer: "San Jose, custodio del Redentor, ruega por nosotros.",
    period: "Siglo I a.C. - Siglo I d.C.",
    image: "/images/saints/san-jose.jpg",
    watercolorFront: "#d4c4a0",
    watercolorBack: "#a8b8a0",
  },
  {
    id: "san-juan-bautista",
    name: "San Juan Bautista",
    title: "SAN",
    displayName: "Juan Bautista",
    feastDay: "24 DE JUNIO",
    virtue: "VOZ DEL QUE CLAMA",
    description: "Precursor de Cristo, bautizo a Jesus en el rio Jordan. Predico la penitencia en el desierto y senalo a Jesus como el Cordero de Dios. Murio martir por defender la verdad.",
    prayer: "He ahi el Cordero de Dios, que quita el pecado del mundo.",
    period: "Siglo I a.C. - 31 d.C.",
    image: "/images/saints/san-juan-bautista.jpg",
    watercolorFront: "#c4b89c",
    watercolorBack: "#9cb8a8",
  },
  {
    id: "san-francisco-de-asis",
    name: "San Francisco de Asis",
    title: "SAN",
    displayName: "Francisco",
    feastDay: "4 DE OCTUBRE",
    virtue: "POBREZA Y ALEGRIA",
    description: "Fundador de la Orden Franciscana, renuncio a toda riqueza para vivir el Evangelio en pobreza radical. Recibio los estigmas y es patron de los animales y la ecologia.",
    prayer: "Senor, hazme instrumento de tu paz.",
    period: "1181 - 1226",
    image: "/images/saints/san-francisco-de-asis.jpg",
    watercolorFront: "#c4b090",
    watercolorBack: "#a8c4a0",
  },
  {
    id: "santo-tomas-de-aquino",
    name: "Santo Tomas de Aquino",
    title: "SANTO",
    displayName: "Tomas de Aquino",
    feastDay: "28 DE ENERO",
    virtue: "SABIDURIA DIVINA",
    description: "Doctor de la Iglesia y teologo dominico. Escribio la Summa Theologica, obra cumbre de la filosofia y teologia cristiana. Su pensamiento sigue iluminando la fe y la razon.",
    prayer: "Concedeme, Senor, penetrar la verdad que mi mente desea conocer.",
    period: "1225 - 1274",
    image: "/images/saints/santo-tomas-de-aquino.jpg",
    watercolorFront: "#a8a8c4",
    watercolorBack: "#c4c4a8",
  },
  {
    id: "santa-teresa-de-calcuta",
    name: "Santa Teresa de Calcuta",
    title: "SANTA",
    displayName: "Teresa de Calcuta",
    feastDay: "5 DE SEPTIEMBRE",
    virtue: "CARIDAD SIN LIMITES",
    description: "Fundadora de las Misioneras de la Caridad, dedico su vida a servir a los mas pobres entre los pobres en las calles de Calcuta. Premio Nobel de la Paz en 1979.",
    prayer: "No podemos hacer grandes cosas, solo pequenas cosas con gran amor.",
    period: "1910 - 1997",
    image: "/images/saints/santa-teresa-de-calcuta.jpg",
    watercolorFront: "#c4d4e0",
    watercolorBack: "#e0d4c4",
  },
  {
    id: "santa-rosa-de-lima",
    name: "Santa Rosa de Lima",
    title: "SANTA",
    displayName: "Rosa de Lima",
    feastDay: "23 DE AGOSTO",
    virtue: "PENITENCIA Y AMOR",
    description: "Primera santa canonizada de America. Terciaria dominica que vivio una vida de extrema penitencia y oracion mistica. Patrona de America Latina y Filipinas.",
    prayer: "Fuera de la Cruz no hay otra escala por donde subir al cielo.",
    period: "1586 - 1617",
    image: "/images/saints/santa-rosa-de-lima.jpg",
    watercolorFront: "#e0b8c0",
    watercolorBack: "#c0d4b8",
  },
  {
    id: "san-miguel-arcangel",
    name: "San Miguel Arcangel",
    title: "SAN",
    displayName: "Miguel Arcangel",
    feastDay: "29 DE SEPTIEMBRE",
    virtue: "DEFENSA DE LA FE",
    description: "Principe de la milicia celestial, lidera a los angeles en la lucha contra el mal. Su nombre significa 'Quien como Dios'. Patron de los soldados y la Iglesia universal.",
    prayer: "San Miguel Arcangel, defiendenos en la batalla.",
    period: "Desde la eternidad",
    image: "/images/saints/san-miguel-arcangel.jpg",
    watercolorFront: "#a0b8d4",
    watercolorBack: "#d4a0a0",
  },
  {
    id: "san-agustin",
    name: "San Agustin",
    title: "SAN",
    displayName: "Agustin",
    feastDay: "28 DE AGOSTO",
    virtue: "CONVERSION DEL CORAZON",
    description: "Obispo de Hipona y Doctor de la Iglesia. Tras una juventud alejada de Dios, se convirtio profundamente. Sus Confesiones y La Ciudad de Dios son obras fundamentales del cristianismo.",
    prayer: "Nos hiciste, Senor, para Ti, y nuestro corazon esta inquieto hasta que descanse en Ti.",
    period: "354 - 430",
    watercolorFront: "#c4a890",
    watercolorBack: "#90a8c4",
  },
  {
    id: "san-ignacio-de-loyola",
    name: "San Ignacio de Loyola",
    title: "SAN",
    displayName: "Ignacio de Loyola",
    feastDay: "31 DE JULIO",
    virtue: "TODO PARA MAYOR GLORIA DE DIOS",
    description: "Fundador de la Compania de Jesus. Soldado vasco que, herido en batalla, se convirtio leyendo vidas de santos. Creo los Ejercicios Espirituales, metodo de oracion y discernimiento.",
    prayer: "Toma, Senor, y recibe toda mi libertad.",
    period: "1491 - 1556",
    watercolorFront: "#a0a8b8",
    watercolorBack: "#b8a8a0",
  },
  {
    id: "santa-teresa-de-jesus",
    name: "Santa Teresa de Jesus",
    title: "SANTA",
    displayName: "Teresa de Jesus",
    feastDay: "15 DE OCTUBRE",
    virtue: "ORACION Y FORTALEZA",
    description: "Doctora de la Iglesia y reformadora del Carmelo. Mistica espanola que escribio obras maestras de la espiritualidad como Las Moradas y Camino de Perfeccion.",
    prayer: "Nada te turbe, nada te espante; solo Dios basta.",
    period: "1515 - 1582",
    watercolorFront: "#d4b8a0",
    watercolorBack: "#a0c4b8",
  },
  {
    id: "san-juan-de-la-cruz",
    name: "San Juan de la Cruz",
    title: "SAN",
    displayName: "Juan de la Cruz",
    feastDay: "14 DE DICIEMBRE",
    virtue: "NOCHE OSCURA DEL ALMA",
    description: "Doctor de la Iglesia y poeta mistico. Reformador del Carmelo junto a Santa Teresa. Su poesia es cumbre de la literatura mistica universal.",
    prayer: "En una noche oscura, con ansias en amores inflamada.",
    period: "1542 - 1591",
    watercolorFront: "#8898b0",
    watercolorBack: "#b0a088",
  },
  {
    id: "san-antonio-de-padua",
    name: "San Antonio de Padua",
    title: "SAN",
    displayName: "Antonio de Padua",
    feastDay: "13 DE JUNIO",
    virtue: "PREDICACION Y MILAGROS",
    description: "Franciscano y Doctor de la Iglesia, conocido como el 'Martillo de los herejes'. Gran predicador y taumaturgo, es invocado para encontrar objetos perdidos.",
    prayer: "San Antonio, luz de la Iglesia, ruega por nosotros.",
    period: "1195 - 1231",
    watercolorFront: "#b8c0a8",
    watercolorBack: "#a8b0c0",
  },
  {
    id: "san-benito",
    name: "San Benito",
    title: "SAN",
    displayName: "Benito",
    feastDay: "11 DE JULIO",
    virtue: "ORA ET LABORA",
    description: "Padre del monacato occidental, fundo la Orden Benedictina y escribio la Santa Regla. Su lema 'Ora et labora' equilibra la oracion con el trabajo manual.",
    prayer: "Ora et labora: reza y trabaja.",
    period: "480 - 547",
    watercolorFront: "#a0a090",
    watercolorBack: "#90a0a0",
  },
  {
    id: "san-francisco-javier",
    name: "San Francisco Javier",
    title: "SAN",
    displayName: "Francisco Javier",
    feastDay: "3 DE DICIEMBRE",
    virtue: "MISION Y ENTREGA",
    description: "Jesuita y misionero, llevo el Evangelio a la India, Japon y China. Bautizo a miles de personas y es patron de las misiones. Murio en la isla de Sancian camino a China.",
    prayer: "Cuantas almas dejan de ir al cielo por falta de quien las ayude.",
    period: "1506 - 1552",
    watercolorFront: "#90b8c4",
    watercolorBack: "#c4b890",
  },
  {
    id: "santa-catalina-de-siena",
    name: "Santa Catalina de Siena",
    title: "SANTA",
    displayName: "Catalina de Siena",
    feastDay: "29 DE ABRIL",
    virtue: "VERDAD Y VALENTIA",
    description: "Doctora de la Iglesia y terciaria dominica. Mistica y consejera de papas, logro el retorno del papado de Avignon a Roma. Su Dialogo es obra maestra de la espiritualidad.",
    prayer: "Se quien Dios quiere que seas y prenderas fuego al mundo.",
    period: "1347 - 1380",
    watercolorFront: "#d4a8b8",
    watercolorBack: "#b8d4a8",
  },
  {
    id: "san-martin-de-porres",
    name: "San Martin de Porres",
    title: "SAN",
    displayName: "Martin de Porres",
    feastDay: "3 DE NOVIEMBRE",
    virtue: "HUMILDAD Y SERVICIO",
    description: "Dominico peruano, hijo de un espanol y una negra libre. Dedico su vida a los enfermos y pobres. Tenia don de bilocacion y curacion. Patron de la justicia social.",
    prayer: "Senor, todo lo que tengo es tuyo; disponed de mi segun tu voluntad.",
    period: "1579 - 1639",
    watercolorFront: "#c4a890",
    watercolorBack: "#90c4a8",
  },
  {
    id: "san-juan-bosco",
    name: "San Juan Bosco",
    title: "SAN",
    displayName: "Juan Bosco",
    feastDay: "31 DE ENERO",
    virtue: "EDUCACION CON AMOR",
    description: "Fundador de los Salesianos, dedico su vida a la educacion de jovenes pobres y abandonados. Su sistema preventivo se basa en razon, religion y amabilidad.",
    prayer: "Basta que seais jovenes para que yo os ame.",
    period: "1815 - 1888",
    watercolorFront: "#a8b8d0",
    watercolorBack: "#d0b8a8",
  },
  {
    id: "santa-teresita-del-nino-jesus",
    name: "Santa Teresita del Nino Jesus",
    title: "SANTA",
    displayName: "Teresita",
    feastDay: "1 DE OCTUBRE",
    virtue: "EL CAMINITO PEQUENO",
    description: "Carmelita descalza y Doctora de la Iglesia. Su 'caminito' de infancia espiritual revoluciono la espiritualidad. Patrona de las misiones pese a no haber salido del convento.",
    prayer: "Mi vocacion es el amor; en el corazon de la Iglesia sere el amor.",
    period: "1873 - 1897",
    watercolorFront: "#e0c8d0",
    watercolorBack: "#d0e0c8",
  },
  {
    id: "san-patricio",
    name: "San Patricio",
    title: "SAN",
    displayName: "Patricio",
    feastDay: "17 DE MARZO",
    virtue: "EVANGELIZACION",
    description: "Apostol de Irlanda, fue esclavizado de joven y tras escapar regreso a evangelizar la isla. Uso el trebol para explicar la Santisima Trinidad. Patron de Irlanda.",
    prayer: "Cristo conmigo, Cristo ante mi, Cristo detras de mi.",
    period: "385 - 461",
    watercolorFront: "#90c4a0",
    watercolorBack: "#a0b4c4",
  },
  {
    id: "san-jorge",
    name: "San Jorge",
    title: "SAN",
    displayName: "Jorge",
    feastDay: "23 DE ABRIL",
    virtue: "VALOR CRISTIANO",
    description: "Soldado romano y martir, la leyenda cuenta que mato a un dragon para salvar a una princesa, simbolo de la victoria del bien sobre el mal. Patron de Inglaterra y Cataluna.",
    prayer: "San Jorge, danos valor para vencer el mal con el bien.",
    period: "275 - 303",
    watercolorFront: "#c4a0a0",
    watercolorBack: "#a0a0c4",
  },
  {
    id: "san-santiago-apostol",
    name: "Santiago Apostol",
    title: "SAN",
    displayName: "Santiago",
    feastDay: "25 DE JULIO",
    virtue: "PEREGRINACION",
    description: "Apostol de Jesus e hijo de Zebedeo. Segun la tradicion, predico en Hispania. Sus restos se veneran en Santiago de Compostela, destino del famoso Camino.",
    prayer: "Buen Camino; Santiago, guia nuestros pasos.",
    period: "Siglo I d.C.",
    watercolorFront: "#b8a890",
    watercolorBack: "#90b8a8",
  },
  {
    id: "san-andres-apostol",
    name: "San Andres Apostol",
    title: "SAN",
    displayName: "Andres",
    feastDay: "30 DE NOVIEMBRE",
    virtue: "PRIMER LLAMADO",
    description: "Hermano de San Pedro y primer discipulo llamado por Jesus. Predico el Evangelio en Grecia y fue crucificado en una cruz en forma de X. Patron de Escocia y Rusia.",
    prayer: "Hemos encontrado al Mesias.",
    period: "Siglo I d.C.",
    watercolorFront: "#a0b0c4",
    watercolorBack: "#c4b0a0",
  },
  {
    id: "san-marcos-evangelista",
    name: "San Marcos Evangelista",
    title: "SAN",
    displayName: "Marcos",
    feastDay: "25 DE ABRIL",
    virtue: "TESTIMONIO ESCRITO",
    description: "Autor del segundo Evangelio, companero de San Pedro y San Pablo en sus viajes misioneros. Fundo la Iglesia de Alejandria. Su simbolo es el leon alado.",
    prayer: "Principio del Evangelio de Jesucristo, Hijo de Dios.",
    period: "Siglo I d.C.",
    watercolorFront: "#c4b4a0",
    watercolorBack: "#a0b4c4",
  },
  {
    id: "san-lucas-evangelista",
    name: "San Lucas Evangelista",
    title: "SAN",
    displayName: "Lucas",
    feastDay: "18 DE OCTUBRE",
    virtue: "ARTE Y EVANGELIO",
    description: "Medico y companero de San Pablo, autor del tercer Evangelio y los Hechos de los Apostoles. Segun la tradicion, pinto el primer icono de la Virgen Maria. Patron de los medicos y artistas.",
    prayer: "El Senor ha hecho obras grandes por mi; santo es su Nombre.",
    period: "Siglo I d.C.",
    watercolorFront: "#a8c0b0",
    watercolorBack: "#b0a8c0",
  },
  {
    id: "san-mateo-apostol",
    name: "San Mateo Apostol",
    title: "SAN",
    displayName: "Mateo",
    feastDay: "21 DE SEPTIEMBRE",
    virtue: "CONVERSION TOTAL",
    description: "Recaudador de impuestos que dejo todo para seguir a Jesus. Autor del primer Evangelio, donde muestra a Jesus como el Mesias prometido. Patron de los contadores.",
    prayer: "Sigueme, dijo Jesus; y el, levantandose, le siguio.",
    period: "Siglo I d.C.",
    watercolorFront: "#b8a8b0",
    watercolorBack: "#b0b8a8",
  },
  {
    id: "san-juan-evangelista",
    name: "San Juan Evangelista",
    title: "SAN",
    displayName: "Juan Evangelista",
    feastDay: "27 DE DICIEMBRE",
    virtue: "AMOR FRATERNO",
    description: "El discipulo amado, autor del cuarto Evangelio, tres epistolas y el Apocalipsis. Unico apostol que no murio martir. Cuido de la Virgen Maria tras la crucifixion.",
    prayer: "Hijitos, amaos los unos a los otros.",
    period: "6 d.C. - 100 d.C.",
    watercolorFront: "#a0b8c8",
    watercolorBack: "#c8b8a0",
  },
  {
    id: "san-nicolas-de-bari",
    name: "San Nicolas de Bari",
    title: "SAN",
    displayName: "Nicolas de Bari",
    feastDay: "6 DE DICIEMBRE",
    virtue: "GENEROSIDAD",
    description: "Obispo de Mira, famoso por su generosidad con los pobres. La leyenda de sus regalos secretos a tres doncellas inspiro la tradicion de Santa Claus.",
    prayer: "Dad y se os dara; la generosidad es el reflejo de Dios.",
    period: "270 - 343",
    watercolorFront: "#c4a0a8",
    watercolorBack: "#a8c4a0",
  },
  {
    id: "santa-lucia",
    name: "Santa Lucia",
    title: "SANTA",
    displayName: "Lucia",
    feastDay: "13 DE DICIEMBRE",
    virtue: "LUZ EN LA OSCURIDAD",
    description: "Virgen y martir siciliana que consagro su virginidad a Cristo. Fue denunciada durante la persecucion de Diocleciano. Patrona de los ciegos y de la vista.",
    prayer: "Santa Lucia, ilumina nuestro camino con la luz de Cristo.",
    period: "283 - 304",
    watercolorFront: "#d4d0b8",
    watercolorBack: "#b8c4d4",
  },
  {
    id: "santa-cecilia",
    name: "Santa Cecilia",
    title: "SANTA",
    displayName: "Cecilia",
    feastDay: "22 DE NOVIEMBRE",
    virtue: "ARMONIA CELESTIAL",
    description: "Virgen y martir romana. Segun la tradicion, cantaba himnos a Dios en su corazon durante su boda. Patrona de los musicos y la musica sacra.",
    prayer: "Cantad al Senor un cantico nuevo.",
    period: "Siglo II - III d.C.",
    watercolorFront: "#c8b8d0",
    watercolorBack: "#d0c8b8",
  },
  {
    id: "san-sebastian",
    name: "San Sebastian",
    title: "SAN",
    displayName: "Sebastian",
    feastDay: "20 DE ENERO",
    virtue: "FORTALEZA ANTE EL MARTIRIO",
    description: "Soldado romano y capitan de la guardia pretoriana. Al descubrirse su fe cristiana, fue atado a un poste y asaeteado. Sobrevivio y fue finalmente martirizado a golpes.",
    prayer: "San Sebastian, danos fortaleza en la prueba.",
    period: "256 - 288",
    watercolorFront: "#b0a098",
    watercolorBack: "#98b0a0",
  },
  {
    id: "santo-domingo-de-guzman",
    name: "Santo Domingo de Guzman",
    title: "SANTO",
    displayName: "Domingo de Guzman",
    feastDay: "8 DE AGOSTO",
    virtue: "PREDICAR LA VERDAD",
    description: "Fundador de la Orden de Predicadores (Dominicos). Combatio la herejia albigense con la predicacion y la oracion. Se le atribuye la difusion del Santo Rosario.",
    prayer: "Contemplar la verdad y compartirla con los demas.",
    period: "1170 - 1221",
    watercolorFront: "#a8a8b8",
    watercolorBack: "#b8a8a8",
  },
  {
    id: "san-felipe-neri",
    name: "San Felipe Neri",
    title: "SAN",
    displayName: "Felipe Neri",
    feastDay: "26 DE MAYO",
    virtue: "ALEGRIA DEL EVANGELIO",
    description: "Apostol de Roma y fundador del Oratorio. Conocido como el 'santo de la alegria' por su buen humor y cercania con la gente. Atraia a jovenes y ancianos por igual.",
    prayer: "Estad alegres en el Senor; un santo triste es un triste santo.",
    period: "1515 - 1595",
    watercolorFront: "#c0b8a0",
    watercolorBack: "#a0c0b8",
  },
  {
    id: "san-carlos-borromeo",
    name: "San Carlos Borromeo",
    title: "SAN",
    displayName: "Carlos Borromeo",
    feastDay: "4 DE NOVIEMBRE",
    virtue: "REFORMA Y ENTREGA",
    description: "Arzobispo de Milan y figura clave del Concilio de Trento. Reformo la Iglesia con su ejemplo, fundo seminarios y sirvio heroicamente durante la peste de Milan.",
    prayer: "Las almas se ganan de rodillas.",
    period: "1538 - 1584",
    watercolorFront: "#b0a8b8",
    watercolorBack: "#b8b0a8",
  },
  {
    id: "san-francisco-de-sales",
    name: "San Francisco de Sales",
    title: "SAN",
    displayName: "Francisco de Sales",
    feastDay: "24 DE ENERO",
    virtue: "DULZURA Y PIEDAD",
    description: "Obispo de Ginebra y Doctor de la Iglesia. Reconquisto para la fe catolica el Chablais. Su 'Introduccion a la Vida Devota' sigue siendo guia espiritual para laicos.",
    prayer: "Con una gota de miel se cazan mas moscas que con un barril de vinagre.",
    period: "1567 - 1622",
    watercolorFront: "#b8c4b0",
    watercolorBack: "#b0b8c4",
  },
  {
    id: "santa-clara-de-asis",
    name: "Santa Clara de Asis",
    title: "SANTA",
    displayName: "Clara de Asis",
    feastDay: "11 DE AGOSTO",
    virtue: "POBREZA RADICAL",
    description: "Seguidora de San Francisco, fundo la Orden de las Clarisas. Vivio en absoluta pobreza y contemplacion. Patrona de la television por haber visto la Misa a distancia.",
    prayer: "Amad a Dios de todo corazon y seguid sus huellas en pobreza.",
    period: "1194 - 1253",
    watercolorFront: "#c8d0c0",
    watercolorBack: "#c0c8d0",
  },
  {
    id: "san-alfonso-maria-de-ligorio",
    name: "San Alfonso Maria de Ligorio",
    title: "SAN",
    displayName: "Alfonso de Ligorio",
    feastDay: "1 DE AGOSTO",
    virtue: "MISERICORDIA PASTORAL",
    description: "Fundador de los Redentoristas y Doctor de la Iglesia. Abogado que dejo las leyes para ser sacerdote. Su teologia moral sigue siendo referencia en la Iglesia.",
    prayer: "Quien reza se salva; quien no reza se condena.",
    period: "1696 - 1787",
    watercolorFront: "#c0a8b0",
    watercolorBack: "#b0c0a8",
  },
  {
    id: "san-juan-maria-vianney",
    name: "San Juan Maria Vianney",
    title: "SAN",
    displayName: "Juan M. Vianney",
    feastDay: "4 DE AGOSTO",
    virtue: "CURA DE ALMAS",
    description: "El Santo Cura de Ars, dedicaba hasta 16 horas diarias al confesionario. Transformo una parroquia indiferente en modelo de fe. Patron de los sacerdotes y parrocos.",
    prayer: "El sacerdocio es el amor del corazon de Jesus.",
    period: "1786 - 1859",
    watercolorFront: "#a8b0a8",
    watercolorBack: "#a8a8b0",
  },
  {
    id: "san-pio-de-pietrelcina",
    name: "San Pio de Pietrelcina",
    title: "SAN",
    displayName: "Padre Pio",
    feastDay: "23 DE SEPTIEMBRE",
    virtue: "SUFRIMIENTO REDENTOR",
    description: "Capuchino italiano que llevo los estigmas durante 50 anos. Famoso por sus dones de bilocacion, lectura de conciencias y curaciones. Fundo el hospital Casa Sollievo.",
    prayer: "Reza, espera, no te preocupes.",
    period: "1887 - 1968",
    watercolorFront: "#b0a8a0",
    watercolorBack: "#a0b0a8",
  },
  {
    id: "san-juan-pablo-ii",
    name: "San Juan Pablo II",
    title: "SAN",
    displayName: "Juan Pablo II",
    feastDay: "22 DE OCTUBRE",
    virtue: "NO TENGAIS MIEDO",
    description: "Papa polaco que lidero la Iglesia durante 27 anos. Contribuyo a la caida del comunismo, viajo por todo el mundo y proclamo la cultura de la vida y la civilizacion del amor.",
    prayer: "No tengais miedo; abrid de par en par las puertas a Cristo.",
    period: "1920 - 2005",
    watercolorFront: "#d0c8b8",
    watercolorBack: "#b8c8d0",
  },
  {
    id: "san-josemaria-escriva",
    name: "San Josemaria Escriva",
    title: "SAN",
    displayName: "Josemaria Escriva",
    feastDay: "26 DE JUNIO",
    virtue: "SANTIDAD EN LO ORDINARIO",
    description: "Fundador del Opus Dei, ensenando que todos estan llamados a la santidad en su trabajo y vida ordinaria. Su mensaje ha transformado la espiritualidad laical.",
    prayer: "Santifica tu trabajo, santificate en el trabajo, santifica con el trabajo.",
    period: "1902 - 1975",
    watercolorFront: "#b8b0a8",
    watercolorBack: "#a8b8b0",
  },
  {
    id: "santa-faustina-kowalska",
    name: "Santa Faustina Kowalska",
    title: "SANTA",
    displayName: "Faustina Kowalska",
    feastDay: "5 DE OCTUBRE",
    virtue: "DIVINA MISERICORDIA",
    description: "Religiosa polaca a quien Jesus revelo el mensaje de la Divina Misericordia. Su diario espiritual y la imagen de Jesus Misericordioso son conocidos en todo el mundo.",
    prayer: "Jesus, en Ti confio.",
    period: "1905 - 1938",
    watercolorFront: "#c0c8d4",
    watercolorBack: "#d4c0c0",
  },
  {
    id: "san-maximiliano-kolbe",
    name: "San Maximiliano Kolbe",
    title: "SAN",
    displayName: "Maximiliano Kolbe",
    feastDay: "14 DE AGOSTO",
    virtue: "AMOR HASTA EL FIN",
    description: "Franciscano polaco que ofrecio su vida en lugar de otro prisionero en Auschwitz. Fundador de la Milicia de la Inmaculada y gran apostol mariano.",
    prayer: "Nadie tiene mayor amor que el que da la vida por sus amigos.",
    period: "1894 - 1941",
    watercolorFront: "#a8b8c0",
    watercolorBack: "#c0a8b8",
  },
  {
    id: "santa-edith-stein",
    name: "Santa Edith Stein",
    title: "SANTA",
    displayName: "Edith Stein",
    feastDay: "9 DE AGOSTO",
    virtue: "BUSQUEDA DE LA VERDAD",
    description: "Filosofa judia convertida al catolicismo, carmelita descalza con el nombre Teresa Benedicta de la Cruz. Murio en Auschwitz. Patrona de Europa.",
    prayer: "Quien busca la verdad, busca a Dios, lo sepa o no.",
    period: "1891 - 1942",
    watercolorFront: "#b8a8c0",
    watercolorBack: "#c0b8a8",
  },
  {
    id: "san-oscar-romero",
    name: "San Oscar Romero",
    title: "SAN",
    displayName: "Oscar Romero",
    feastDay: "24 DE MARZO",
    virtue: "VOZ DE LOS SIN VOZ",
    description: "Arzobispo de San Salvador, defensor de los pobres y los derechos humanos. Fue asesinado mientras celebraba la Misa. Martir de la justicia y la caridad.",
    prayer: "La paz no es la ausencia de guerra, sino la obra de la justicia.",
    period: "1917 - 1980",
    watercolorFront: "#c4b8a0",
    watercolorBack: "#a0b8c4",
  },
  {
    id: "san-rafael-arcangel",
    name: "San Rafael Arcangel",
    title: "SAN",
    displayName: "Rafael Arcangel",
    feastDay: "29 DE SEPTIEMBRE",
    virtue: "SANACION DIVINA",
    description: "Arcangel cuyo nombre significa 'Dios sana'. Acompano a Tobias en su viaje y curo la ceguera de su padre. Patron de los viajeros, medicos y enfermos.",
    prayer: "San Rafael, medicina de Dios, acompananos en el camino.",
    period: "Desde la eternidad",
    watercolorFront: "#a0c4b0",
    watercolorBack: "#b0a0c4",
  },
  {
    id: "san-gabriel-arcangel",
    name: "San Gabriel Arcangel",
    title: "SAN",
    displayName: "Gabriel Arcangel",
    feastDay: "29 DE SEPTIEMBRE",
    virtue: "MENSAJERO DE DIOS",
    description: "Arcangel que anuncio a la Virgen Maria la Encarnacion del Hijo de Dios. Su nombre significa 'Fuerza de Dios'. Patron de las comunicaciones y los mensajeros.",
    prayer: "Ave Maria, llena eres de gracia, el Senor es contigo.",
    period: "Desde la eternidad",
    watercolorFront: "#b0c4a0",
    watercolorBack: "#a0b0c4",
  },
]

export function getSaintById(id: string): Saint | undefined {
  return saints.find(s => s.id === id)
}

export function searchSaints(query: string): Saint[] {
  const q = query.toLowerCase()
  return saints.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.displayName.toLowerCase().includes(q) ||
    s.feastDay.toLowerCase().includes(q) ||
    s.virtue.toLowerCase().includes(q)
  )
}

export function saintsAsBookmarkItems(): BookmarkItem[] {
  return saints.map(s => ({
    id: s.id,
    name: s.name,
    prefix: s.title,
    displayName: s.displayName,
    subtitle: s.feastDay,
    tagline: s.virtue,
    description: s.description,
    metadata: s.period,
    quote: s.prayer,
    image: s.image,
    colorFront: s.watercolorFront,
    colorBack: s.watercolorBack,
  }))
}
